size: 9
title: "Игровое значение"
items:
  slot0:
    type: WRITABLE_BOOK
    amount: 1
    name: '§f Сообщение игрока '
    lore:
      - '§f Получает сообщение игрока из события '
      - '§f'
      - '§f Работает с:'
      - '§e > §fСобытие чата'